FROM alpine:3.9

WORKDIR /app

COPY Gemfile* /app/

RUN apk --no-cache --update add build-base ruby-dev \
     && gem install bundler:1.17.2 --no-document \
     && bundle install \
     && apk del build-base ruby-dev

COPY . /app

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
