---
- name: Setup GitLab Runner
  hosts: all
  become: true
  tasks:
    - name: Create config directory
      file:
        name: /srv/gitlab-runner/config
        state: directory
        mode: 0755

    - name: Run GitLab Runner
      community.docker.docker_container:
        name: gitlab-runner
        hostname: gitlab-runner
        image: gitlab/gitlab-runner:latest
        state: started
        restart_policy: always
        container_default_behavior: no_defaults
        volumes:
          - /srv/gitlab-runner/config:/etc/gitlab-runner
          - /var/run/docker.sock:/var/run/docker.sock

    - name: Register GitLab Runner
      community.docker.docker_container_exec:
        container: gitlab-runner
        command: gitlab-runner register --url http://"{{ ansible_host }}" --non-interactive --locked=false --name="DockerRunner" --executor docker --docker-image "alpine:latest" --registration-token "{{ registration_token }}" --tag-list "linux,xenial,ubuntu,docker" --run-untagged
      register: result

    - name: Log result
      debug:
        var: result.stderr_lines
