plugin: yc_compute
folders:
  - hidden
filters:
  - status == 'RUNNING'
auth_kind: serviceaccountfile
service_account_file: key.json
compose:
  ansible_host: network_interfaces[0].primary_v4_address.one_to_one_nat.address
groups:
  master: labels['tags'] == 'master'
  worker: labels['tags'] == 'node'
